// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BatchesColumns holds the columns for the "batches" table.
	BatchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "reference", Type: field.TypeString, Unique: true},
		{Name: "sku", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "eta", Type: field.TypeTime},
	}
	// BatchesTable holds the schema information for the "batches" table.
	BatchesTable = &schema.Table{
		Name:       "batches",
		Columns:    BatchesColumns,
		PrimaryKey: []*schema.Column{BatchesColumns[0]},
	}
	// OrderLinesColumns holds the columns for the "order_lines" table.
	OrderLinesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_id", Type: field.TypeString},
		{Name: "sku", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "batch_order_lines", Type: field.TypeInt, Nullable: true},
	}
	// OrderLinesTable holds the schema information for the "order_lines" table.
	OrderLinesTable = &schema.Table{
		Name:       "order_lines",
		Columns:    OrderLinesColumns,
		PrimaryKey: []*schema.Column{OrderLinesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "order_lines_batches_order_lines",
				Columns:    []*schema.Column{OrderLinesColumns[4]},
				RefColumns: []*schema.Column{BatchesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BatchesTable,
		OrderLinesTable,
	}
)

func init() {
	OrderLinesTable.ForeignKeys[0].RefTable = BatchesTable
}
