// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/abbasegbeyemi/cosmic-python-go/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/abbasegbeyemi/cosmic-python-go/ent/batch"
	"github.com/abbasegbeyemi/cosmic-python-go/ent/orderline"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Batch is the client for interacting with the Batch builders.
	Batch *BatchClient
	// OrderLine is the client for interacting with the OrderLine builders.
	OrderLine *OrderLineClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Batch = NewBatchClient(c.config)
	c.OrderLine = NewOrderLineClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Batch:     NewBatchClient(cfg),
		OrderLine: NewOrderLineClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Batch:     NewBatchClient(cfg),
		OrderLine: NewOrderLineClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Batch.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Batch.Use(hooks...)
	c.OrderLine.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Batch.Intercept(interceptors...)
	c.OrderLine.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BatchMutation:
		return c.Batch.mutate(ctx, m)
	case *OrderLineMutation:
		return c.OrderLine.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BatchClient is a client for the Batch schema.
type BatchClient struct {
	config
}

// NewBatchClient returns a client for the Batch from the given config.
func NewBatchClient(c config) *BatchClient {
	return &BatchClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `batch.Hooks(f(g(h())))`.
func (c *BatchClient) Use(hooks ...Hook) {
	c.hooks.Batch = append(c.hooks.Batch, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `batch.Intercept(f(g(h())))`.
func (c *BatchClient) Intercept(interceptors ...Interceptor) {
	c.inters.Batch = append(c.inters.Batch, interceptors...)
}

// Create returns a builder for creating a Batch entity.
func (c *BatchClient) Create() *BatchCreate {
	mutation := newBatchMutation(c.config, OpCreate)
	return &BatchCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Batch entities.
func (c *BatchClient) CreateBulk(builders ...*BatchCreate) *BatchCreateBulk {
	return &BatchCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BatchClient) MapCreateBulk(slice any, setFunc func(*BatchCreate, int)) *BatchCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BatchCreateBulk{err: fmt.Errorf("calling to BatchClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BatchCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BatchCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Batch.
func (c *BatchClient) Update() *BatchUpdate {
	mutation := newBatchMutation(c.config, OpUpdate)
	return &BatchUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BatchClient) UpdateOne(b *Batch) *BatchUpdateOne {
	mutation := newBatchMutation(c.config, OpUpdateOne, withBatch(b))
	return &BatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BatchClient) UpdateOneID(id int) *BatchUpdateOne {
	mutation := newBatchMutation(c.config, OpUpdateOne, withBatchID(id))
	return &BatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Batch.
func (c *BatchClient) Delete() *BatchDelete {
	mutation := newBatchMutation(c.config, OpDelete)
	return &BatchDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BatchClient) DeleteOne(b *Batch) *BatchDeleteOne {
	return c.DeleteOneID(b.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BatchClient) DeleteOneID(id int) *BatchDeleteOne {
	builder := c.Delete().Where(batch.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BatchDeleteOne{builder}
}

// Query returns a query builder for Batch.
func (c *BatchClient) Query() *BatchQuery {
	return &BatchQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBatch},
		inters: c.Interceptors(),
	}
}

// Get returns a Batch entity by its id.
func (c *BatchClient) Get(ctx context.Context, id int) (*Batch, error) {
	return c.Query().Where(batch.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BatchClient) GetX(ctx context.Context, id int) *Batch {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOrderLines queries the order_lines edge of a Batch.
func (c *BatchClient) QueryOrderLines(b *Batch) *OrderLineQuery {
	query := (&OrderLineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(batch.Table, batch.FieldID, id),
			sqlgraph.To(orderline.Table, orderline.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, batch.OrderLinesTable, batch.OrderLinesColumn),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BatchClient) Hooks() []Hook {
	return c.hooks.Batch
}

// Interceptors returns the client interceptors.
func (c *BatchClient) Interceptors() []Interceptor {
	return c.inters.Batch
}

func (c *BatchClient) mutate(ctx context.Context, m *BatchMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BatchCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BatchUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BatchDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Batch mutation op: %q", m.Op())
	}
}

// OrderLineClient is a client for the OrderLine schema.
type OrderLineClient struct {
	config
}

// NewOrderLineClient returns a client for the OrderLine from the given config.
func NewOrderLineClient(c config) *OrderLineClient {
	return &OrderLineClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `orderline.Hooks(f(g(h())))`.
func (c *OrderLineClient) Use(hooks ...Hook) {
	c.hooks.OrderLine = append(c.hooks.OrderLine, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `orderline.Intercept(f(g(h())))`.
func (c *OrderLineClient) Intercept(interceptors ...Interceptor) {
	c.inters.OrderLine = append(c.inters.OrderLine, interceptors...)
}

// Create returns a builder for creating a OrderLine entity.
func (c *OrderLineClient) Create() *OrderLineCreate {
	mutation := newOrderLineMutation(c.config, OpCreate)
	return &OrderLineCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OrderLine entities.
func (c *OrderLineClient) CreateBulk(builders ...*OrderLineCreate) *OrderLineCreateBulk {
	return &OrderLineCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrderLineClient) MapCreateBulk(slice any, setFunc func(*OrderLineCreate, int)) *OrderLineCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrderLineCreateBulk{err: fmt.Errorf("calling to OrderLineClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrderLineCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrderLineCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OrderLine.
func (c *OrderLineClient) Update() *OrderLineUpdate {
	mutation := newOrderLineMutation(c.config, OpUpdate)
	return &OrderLineUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrderLineClient) UpdateOne(ol *OrderLine) *OrderLineUpdateOne {
	mutation := newOrderLineMutation(c.config, OpUpdateOne, withOrderLine(ol))
	return &OrderLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrderLineClient) UpdateOneID(id int) *OrderLineUpdateOne {
	mutation := newOrderLineMutation(c.config, OpUpdateOne, withOrderLineID(id))
	return &OrderLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OrderLine.
func (c *OrderLineClient) Delete() *OrderLineDelete {
	mutation := newOrderLineMutation(c.config, OpDelete)
	return &OrderLineDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrderLineClient) DeleteOne(ol *OrderLine) *OrderLineDeleteOne {
	return c.DeleteOneID(ol.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrderLineClient) DeleteOneID(id int) *OrderLineDeleteOne {
	builder := c.Delete().Where(orderline.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrderLineDeleteOne{builder}
}

// Query returns a query builder for OrderLine.
func (c *OrderLineClient) Query() *OrderLineQuery {
	return &OrderLineQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrderLine},
		inters: c.Interceptors(),
	}
}

// Get returns a OrderLine entity by its id.
func (c *OrderLineClient) Get(ctx context.Context, id int) (*OrderLine, error) {
	return c.Query().Where(orderline.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrderLineClient) GetX(ctx context.Context, id int) *OrderLine {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBatch queries the batch edge of a OrderLine.
func (c *OrderLineClient) QueryBatch(ol *OrderLine) *BatchQuery {
	query := (&BatchClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ol.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(orderline.Table, orderline.FieldID, id),
			sqlgraph.To(batch.Table, batch.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderline.BatchTable, orderline.BatchColumn),
		)
		fromV = sqlgraph.Neighbors(ol.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OrderLineClient) Hooks() []Hook {
	return c.hooks.OrderLine
}

// Interceptors returns the client interceptors.
func (c *OrderLineClient) Interceptors() []Interceptor {
	return c.inters.OrderLine
}

func (c *OrderLineClient) mutate(ctx context.Context, m *OrderLineMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrderLineCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrderLineUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrderLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrderLineDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OrderLine mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Batch, OrderLine []ent.Hook
	}
	inters struct {
		Batch, OrderLine []ent.Interceptor
	}
)
