// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/abbasegbeyemi/cosmic-python-go/ent/batch"
	"github.com/abbasegbeyemi/cosmic-python-go/ent/orderline"
	"github.com/abbasegbeyemi/cosmic-python-go/ent/predicate"
)

// OrderLineUpdate is the builder for updating OrderLine entities.
type OrderLineUpdate struct {
	config
	hooks    []Hook
	mutation *OrderLineMutation
}

// Where appends a list predicates to the OrderLineUpdate builder.
func (olu *OrderLineUpdate) Where(ps ...predicate.OrderLine) *OrderLineUpdate {
	olu.mutation.Where(ps...)
	return olu
}

// SetOrderID sets the "order_id" field.
func (olu *OrderLineUpdate) SetOrderID(s string) *OrderLineUpdate {
	olu.mutation.SetOrderID(s)
	return olu
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (olu *OrderLineUpdate) SetNillableOrderID(s *string) *OrderLineUpdate {
	if s != nil {
		olu.SetOrderID(*s)
	}
	return olu
}

// SetSku sets the "sku" field.
func (olu *OrderLineUpdate) SetSku(s string) *OrderLineUpdate {
	olu.mutation.SetSku(s)
	return olu
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (olu *OrderLineUpdate) SetNillableSku(s *string) *OrderLineUpdate {
	if s != nil {
		olu.SetSku(*s)
	}
	return olu
}

// SetQuantity sets the "quantity" field.
func (olu *OrderLineUpdate) SetQuantity(i int) *OrderLineUpdate {
	olu.mutation.ResetQuantity()
	olu.mutation.SetQuantity(i)
	return olu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (olu *OrderLineUpdate) SetNillableQuantity(i *int) *OrderLineUpdate {
	if i != nil {
		olu.SetQuantity(*i)
	}
	return olu
}

// AddQuantity adds i to the "quantity" field.
func (olu *OrderLineUpdate) AddQuantity(i int) *OrderLineUpdate {
	olu.mutation.AddQuantity(i)
	return olu
}

// SetBatchID sets the "batch" edge to the Batch entity by ID.
func (olu *OrderLineUpdate) SetBatchID(id int) *OrderLineUpdate {
	olu.mutation.SetBatchID(id)
	return olu
}

// SetNillableBatchID sets the "batch" edge to the Batch entity by ID if the given value is not nil.
func (olu *OrderLineUpdate) SetNillableBatchID(id *int) *OrderLineUpdate {
	if id != nil {
		olu = olu.SetBatchID(*id)
	}
	return olu
}

// SetBatch sets the "batch" edge to the Batch entity.
func (olu *OrderLineUpdate) SetBatch(b *Batch) *OrderLineUpdate {
	return olu.SetBatchID(b.ID)
}

// Mutation returns the OrderLineMutation object of the builder.
func (olu *OrderLineUpdate) Mutation() *OrderLineMutation {
	return olu.mutation
}

// ClearBatch clears the "batch" edge to the Batch entity.
func (olu *OrderLineUpdate) ClearBatch() *OrderLineUpdate {
	olu.mutation.ClearBatch()
	return olu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (olu *OrderLineUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, olu.sqlSave, olu.mutation, olu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (olu *OrderLineUpdate) SaveX(ctx context.Context) int {
	affected, err := olu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (olu *OrderLineUpdate) Exec(ctx context.Context) error {
	_, err := olu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (olu *OrderLineUpdate) ExecX(ctx context.Context) {
	if err := olu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (olu *OrderLineUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(orderline.Table, orderline.Columns, sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt))
	if ps := olu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := olu.mutation.OrderID(); ok {
		_spec.SetField(orderline.FieldOrderID, field.TypeString, value)
	}
	if value, ok := olu.mutation.Sku(); ok {
		_spec.SetField(orderline.FieldSku, field.TypeString, value)
	}
	if value, ok := olu.mutation.Quantity(); ok {
		_spec.SetField(orderline.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := olu.mutation.AddedQuantity(); ok {
		_spec.AddField(orderline.FieldQuantity, field.TypeInt, value)
	}
	if olu.mutation.BatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.BatchTable,
			Columns: []string{orderline.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batch.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := olu.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.BatchTable,
			Columns: []string{orderline.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, olu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	olu.mutation.done = true
	return n, nil
}

// OrderLineUpdateOne is the builder for updating a single OrderLine entity.
type OrderLineUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderLineMutation
}

// SetOrderID sets the "order_id" field.
func (oluo *OrderLineUpdateOne) SetOrderID(s string) *OrderLineUpdateOne {
	oluo.mutation.SetOrderID(s)
	return oluo
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (oluo *OrderLineUpdateOne) SetNillableOrderID(s *string) *OrderLineUpdateOne {
	if s != nil {
		oluo.SetOrderID(*s)
	}
	return oluo
}

// SetSku sets the "sku" field.
func (oluo *OrderLineUpdateOne) SetSku(s string) *OrderLineUpdateOne {
	oluo.mutation.SetSku(s)
	return oluo
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (oluo *OrderLineUpdateOne) SetNillableSku(s *string) *OrderLineUpdateOne {
	if s != nil {
		oluo.SetSku(*s)
	}
	return oluo
}

// SetQuantity sets the "quantity" field.
func (oluo *OrderLineUpdateOne) SetQuantity(i int) *OrderLineUpdateOne {
	oluo.mutation.ResetQuantity()
	oluo.mutation.SetQuantity(i)
	return oluo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (oluo *OrderLineUpdateOne) SetNillableQuantity(i *int) *OrderLineUpdateOne {
	if i != nil {
		oluo.SetQuantity(*i)
	}
	return oluo
}

// AddQuantity adds i to the "quantity" field.
func (oluo *OrderLineUpdateOne) AddQuantity(i int) *OrderLineUpdateOne {
	oluo.mutation.AddQuantity(i)
	return oluo
}

// SetBatchID sets the "batch" edge to the Batch entity by ID.
func (oluo *OrderLineUpdateOne) SetBatchID(id int) *OrderLineUpdateOne {
	oluo.mutation.SetBatchID(id)
	return oluo
}

// SetNillableBatchID sets the "batch" edge to the Batch entity by ID if the given value is not nil.
func (oluo *OrderLineUpdateOne) SetNillableBatchID(id *int) *OrderLineUpdateOne {
	if id != nil {
		oluo = oluo.SetBatchID(*id)
	}
	return oluo
}

// SetBatch sets the "batch" edge to the Batch entity.
func (oluo *OrderLineUpdateOne) SetBatch(b *Batch) *OrderLineUpdateOne {
	return oluo.SetBatchID(b.ID)
}

// Mutation returns the OrderLineMutation object of the builder.
func (oluo *OrderLineUpdateOne) Mutation() *OrderLineMutation {
	return oluo.mutation
}

// ClearBatch clears the "batch" edge to the Batch entity.
func (oluo *OrderLineUpdateOne) ClearBatch() *OrderLineUpdateOne {
	oluo.mutation.ClearBatch()
	return oluo
}

// Where appends a list predicates to the OrderLineUpdate builder.
func (oluo *OrderLineUpdateOne) Where(ps ...predicate.OrderLine) *OrderLineUpdateOne {
	oluo.mutation.Where(ps...)
	return oluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (oluo *OrderLineUpdateOne) Select(field string, fields ...string) *OrderLineUpdateOne {
	oluo.fields = append([]string{field}, fields...)
	return oluo
}

// Save executes the query and returns the updated OrderLine entity.
func (oluo *OrderLineUpdateOne) Save(ctx context.Context) (*OrderLine, error) {
	return withHooks(ctx, oluo.sqlSave, oluo.mutation, oluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (oluo *OrderLineUpdateOne) SaveX(ctx context.Context) *OrderLine {
	node, err := oluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (oluo *OrderLineUpdateOne) Exec(ctx context.Context) error {
	_, err := oluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oluo *OrderLineUpdateOne) ExecX(ctx context.Context) {
	if err := oluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (oluo *OrderLineUpdateOne) sqlSave(ctx context.Context) (_node *OrderLine, err error) {
	_spec := sqlgraph.NewUpdateSpec(orderline.Table, orderline.Columns, sqlgraph.NewFieldSpec(orderline.FieldID, field.TypeInt))
	id, ok := oluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderLine.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := oluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderline.FieldID)
		for _, f := range fields {
			if !orderline.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderline.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := oluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := oluo.mutation.OrderID(); ok {
		_spec.SetField(orderline.FieldOrderID, field.TypeString, value)
	}
	if value, ok := oluo.mutation.Sku(); ok {
		_spec.SetField(orderline.FieldSku, field.TypeString, value)
	}
	if value, ok := oluo.mutation.Quantity(); ok {
		_spec.SetField(orderline.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := oluo.mutation.AddedQuantity(); ok {
		_spec.AddField(orderline.FieldQuantity, field.TypeInt, value)
	}
	if oluo.mutation.BatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.BatchTable,
			Columns: []string{orderline.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batch.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := oluo.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderline.BatchTable,
			Columns: []string{orderline.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderLine{config: oluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, oluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	oluo.mutation.done = true
	return _node, nil
}
