// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/abbasegbeyemi/cosmic-python-go/ent/batch"
	"github.com/abbasegbeyemi/cosmic-python-go/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	batchFields := schema.Batch{}.Fields()
	_ = batchFields
	// batchDescQuantity is the schema descriptor for quantity field.
	batchDescQuantity := batchFields[2].Descriptor()
	// batch.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	batch.QuantityValidator = batchDescQuantity.Validators[0].(func(int) error)
}
