// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Batch is the predicate function for batch builders.
type Batch func(*sql.Selector)

// OrderLine is the predicate function for orderline builders.
type OrderLine func(*sql.Selector)
